"""
agents/web_agent.py
Web development skill agent — scaffolds HTML, CSS, JS, and Python
web frameworks (FastAPI, Flask). Generates clean boilerplate code.
"""

from typing import Any, Dict
from agents.base_agent import BaseAgent


class WebAgent(BaseAgent):
    """
    Web Builder Agent for frontend and backend scaffolding.

    Capabilities:
    - Generate HTML/CSS/JS templates
    - Scaffold FastAPI and Flask applications
    - Generate REST API endpoint stubs
    - Create responsive UI components
    """

    SUPPORTED_KEYWORDS = [
        "website", "html", "css", "frontend", "backend", "api",
        "fastapi", "flask", "django", "javascript", "scaffold",
        "endpoint", "route", "template", "landing", "page",
    ]

    def __init__(self, memory=None, config: Dict[str, Any] = None):
        super().__init__(memory, config)
        self.logger.info("WebAgent initialized")

    def can_handle(self, task: str) -> bool:
        task_lower = task.lower()
        return any(kw in task_lower for kw in self.SUPPORTED_KEYWORDS)

    def execute(self, task: str) -> str:
        """Route web task to appropriate scaffold generator."""
        self.logger.info(f"WebAgent executing: {task[:60]}...")
        task_lower = task.lower()

        if "fastapi" in task_lower or "api" in task_lower:
            return self._scaffold_fastapi(task)
        elif "flask" in task_lower:
            return self._scaffold_flask(task)
        elif "html" in task_lower or "frontend" in task_lower or "landing" in task_lower:
            return self._scaffold_html(task)
        else:
            return self._scaffold_fastapi(task)

    def _scaffold_fastapi(self, task: str) -> str:
        return '''# FastAPI Application Scaffold
# Generated by WebAgent — Self-Improving AI Agent System

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List
import uvicorn

app = FastAPI(
    title="AI-Generated API",
    description="Auto-scaffolded by skytech45/self-improving-ai-agent",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Models ─────────────────────────────────────────────
class Item(BaseModel):
    id: Optional[int] = None
    name: str
    description: Optional[str] = None
    active: bool = True

# In-memory store (replace with DB in production)
items_db: List[Item] = []

# ── Routes ─────────────────────────────────────────────
@app.get("/", tags=["Root"])
async def root():
    return {"message": "API is running", "status": "ok"}

@app.get("/items", response_model=List[Item], tags=["Items"])
async def get_items():
    return items_db

@app.post("/items", response_model=Item, tags=["Items"])
async def create_item(item: Item):
    item.id = len(items_db) + 1
    items_db.append(item)
    return item

@app.get("/items/{item_id}", response_model=Item, tags=["Items"])
async def get_item(item_id: int):
    for item in items_db:
        if item.id == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")

@app.delete("/items/{item_id}", tags=["Items"])
async def delete_item(item_id: int):
    global items_db
    items_db = [i for i in items_db if i.id != item_id]
    return {"message": f"Item {item_id} deleted"}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''

    def _scaffold_flask(self, task: str) -> str:
        return '''# Flask Application Scaffold
from flask import Flask, jsonify, request
from typing import Dict, Any

app = Flask(__name__)
items = {}
counter = 0

@app.route("/", methods=["GET"])
def index():
    return jsonify({"status": "ok", "message": "Flask app running"})

@app.route("/items", methods=["GET"])
def list_items():
    return jsonify(list(items.values()))

@app.route("/items", methods=["POST"])
def create_item():
    global counter
    data: Dict[str, Any] = request.get_json()
    counter += 1
    items[counter] = {**data, "id": counter}
    return jsonify(items[counter]), 201

if __name__ == "__main__":
    app.run(debug=True, port=5000)
'''

    def _scaffold_html(self, task: str) -> str:
        return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Generated Page</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: "Segoe UI", sans-serif; background: #0f0f0f; color: #eee; }
        header { background: #1a1a2e; padding: 1.5rem 2rem; display: flex;
                 justify-content: space-between; align-items: center; }
        header h1 { color: #00d4ff; font-size: 1.5rem; }
        nav a { color: #ccc; margin-left: 1.5rem; text-decoration: none; }
        nav a:hover { color: #00d4ff; }
        .hero { text-align: center; padding: 5rem 2rem;
                background: linear-gradient(135deg, #1a1a2e, #16213e); }
        .hero h2 { font-size: 2.8rem; color: #00d4ff; margin-bottom: 1rem; }
        .hero p  { font-size: 1.1rem; color: #aaa; max-width: 600px; margin: 0 auto 2rem; }
        .btn { background: #00d4ff; color: #000; padding: .8rem 2rem;
               border: none; border-radius: 5px; cursor: pointer;
               font-size: 1rem; font-weight: bold; text-decoration: none; }
        .btn:hover { background: #00b4d8; }
        footer { text-align: center; padding: 2rem; color: #555; font-size: .85rem; }
    </style>
</head>
<body>
    <header>
        <h1>⚡ skytech45</h1>
        <nav>
            <a href="#">Home</a>
            <a href="#">Projects</a>
            <a href="#">Contact</a>
        </nav>
    </header>
    <section class="hero">
        <h2>Self-Improving AI Agent</h2>
        <p>Autonomous software development, cybersecurity analysis,
           and continuous self-optimization.</p>
        <a href="#" class="btn">Explore Projects</a>
    </section>
    <footer>
        <p>Built by skytech45 | Self-Improving AI Agent System</p>
    </footer>
</body>
</html>
'''
